# Generated by Django 6.1.1 on 2026-09-25 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('service', models.CharField(choices=[('cleaning', 'Dental Cleaning'), ('whitening', 'Teeth Whitening'), ('root_canal', 'Root Canal Treatment'), ('implant', 'Dental Implants'), ('braces', 'Braces & Alignment'), ('kids', 'Kids Dentistry')], max_length=50)),
                ('date', models.DateField()),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
