# Generated by Django 6.1.1 on 2026-09-25 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_clinicsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='email',
            field=models.EmailField(default='old@example.com', max_length=254),
            preserve_default=False,
        ),
    ]
