# Generated by Django 6.1.1 on 2026-09-26 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_appointment_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicsettings',
            name='patients_count',
            field=models.PositiveIntegerField(default=23000),
        ),
        migrations.AddField(
            model_name='clinicsettings',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=4.5, max_digits=3),
        ),
        migrations.AddField(
            model_name='clinicsettings',
            name='years_experience',
            field=models.PositiveIntegerField(default=16),
        ),
        migrations.AlterField(
            model_name='clinicsettings',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='clinic/'),
        ),
    ]
