# Generated by Django 6.1.1 on 2026-09-26 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_clinicsettings_patients_count_clinicsettings_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicsettings',
            name='patients_count',
            field=models.PositiveIntegerField(default=23),
        ),
    ]
