# Generated by Django 6.1.1 on 2026-09-27 05:43

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_gallery_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicsettings',
            name='logo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='logo'),
        ),
    ]
